# Generated by Django 5.2.7 on 2026-01-15 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_user_password_reset_sent_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password_reset_sent_at',
            new_name='account_locked_until',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password_reset_token',
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
