# Generated by Django 5.2.6 on 2025-09-11 02:12


import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_name', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('UNDER_REVIEW', 'Under Review'), ('COMPLETED', 'Completed'), ('POST_REVIEW_PROCESSING', 'Post Review Processing'), ('FAILED', 'Failed'), ('POST_REVIEW_PROCESSING_FAILED', 'Post Review Processing Failed')], default='PENDING', max_length=255)),
                ('docling_json', models.JSONField(blank=True, null=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('other_info', models.JSONField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='chat.chat')),
            ],
            options={
                'verbose_name': 'Uploaded File',
                'verbose_name_plural': 'Uploaded Files',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedTableMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.TextField()),
                ('caption_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_tables', to='uploader.uploadedfile')),
            ],
            options={
                'verbose_name': 'Extracted Table Mapping',
                'verbose_name_plural': 'Extracted Table Mappings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('existing_text', models.TextField(blank=True, null=True)),
                ('comment_type', models.CharField(choices=[('EDIT', 'Edit'), ('REMOVE', 'Remove'), ('TABLE_MERGE', 'Table Merge')], default='EDIT', max_length=20)),
                ('target_ref', models.TextField(blank=True, null=True)),
                ('source_ref', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='uploader.uploadedfile')),
            ],
        ),
    ]
