# Generated by Django 5.2.7 on 2025-10-22 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_knowledge_base'),
        ('uploader', '0002_knowledgebase_uploadedfile_knowledge_base'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='chat',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='uploaded_files',
                to='chat.chat'
            ),
        ),
    ]
