# Generated by Django 5.2.15 on 2026-06-15 10:17

import django.db.models.deletion
import feedback.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=feedback.models.feedback_attachment_upload_to)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=100)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback')),
            ],
            options={
                'verbose_name': 'Feedback attachment',
                'verbose_name_plural': 'Feedback attachments',
                'ordering': ['created_at'],
            },
        ),
    ]
