# Generated by Django 5.2.7 on 2025-10-18 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
        ('uploader', '0002_knowledgebase_uploadedfile_knowledge_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='knowledge_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='uploader.knowledgebase'),
        ),
    ]
