# Generated by Django 5.2.7 on 2025-10-25 04:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chat_knowledge_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Language code (e.g., 'en', 'hi', 'kn')", max_length=10, unique=True)),
                ('name', models.CharField(help_text="Language name (e.g., 'English', 'Hindi', 'Kannada')", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this language is available for selection')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display in dropdown (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
