"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from .utils import get_env_variable
from datetime import timedelta
from sqlalchemy import create_engine

BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Build paths inside the project like this: BASE_DIR / 'subdir'.


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-i7=jb0er2fc08v^*n30t)+0cv#du*vx^5c$4_!513nqv^&w"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = get_env_variable("DEBUG", default=1, boolean=True)

# Security Settings
SECURE_SSL_REDIRECT = False
SESSION_COOKIE_SECURE = get_env_variable("SESSION_COOKIE_SECURE", default=True, boolean=True)
CSRF_COOKIE_SECURE = get_env_variable("CSRF_COOKIE_SECURE", default=True, boolean=True)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

SECURE_HSTS_SECONDS = 31536000  # 1 year
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True

# Session Security - Prevent simultaneous logins
SESSION_SAVE_EVERY_REQUEST = True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Strict'
SESSION_ENGINE = 'django.contrib.sessions.backends.db'

# CSRF Protection
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = 'Strict'
CSRF_USE_SESSIONS = False


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Third-party apps
    "django_celery_beat",
    "django_celery_results",
    "rest_framework",
    "corsheaders",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "health_check",
    "health_check.db",
    "health_check.cache",
    "health_check.storage",
    "channels",
    # Local apps
    "uploader",
    "user_management",
    "chat",
    "application_settings",
    "feedback",
    "reports",
]

# Custom User Model
AUTH_USER_MODEL = "user_management.User"

# MOSPI SMTP API Configuration
PUBLIC_BACKEND_URL = get_env_variable("PUBLIC_BACKEND_URL", default="")
MOSPI_SMTP_AUTH_KEY = get_env_variable("MOSPI_SMTP_AUTH_KEY", "")
DEFAULT_FROM_EMAIL = get_env_variable("DEFAULT_FROM_EMAIL", "noreply.nso.india@mospi.gov.in")

# Legacy Email Configuration (kept as fallback)
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = get_env_variable("EMAIL_HOST", "smtp-mail.outlook.com")
EMAIL_PORT = get_env_variable("EMAIL_PORT", 587, boolean=False)
EMAIL_USE_TLS = get_env_variable("EMAIL_USE_TLS", True, boolean=True)
EMAIL_HOST_USER = get_env_variable("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = get_env_variable("EMAIL_HOST_PASSWORD", "")

# Email Verification Settings
EMAIL_VERIFICATION_TOKEN_EXPIRY_HOURS = 24
EMAIL_VERIFICATION_FROM_EMAIL = DEFAULT_FROM_EMAIL

# Feedback form — comma-separated team inboxes for new submission alerts
FEEDBACK_NOTIFY_EMAILS = get_env_variable(
    "FEEDBACK_NOTIFY_EMAILS", default="di.lab@mospi.gov.in"
)

# MoSPI Data Innovation Lab central feedback portal
MOSPI_PORTAL_FEEDBACK_URL = get_env_variable(
    "MOSPI_PORTAL_FEEDBACK_URL",
    default="https://datainnovation.mospi.gov.in/api/submitFeedback",
)
MOSPI_PORTAL_DATA_SOURCE = get_env_variable("MOSPI_PORTAL_DATA_SOURCE", default="statsdoc")
MOSPI_PORTAL_PRODUCT = get_env_variable("MOSPI_PORTAL_PRODUCT", default="statsdoc")
MOSPI_QUICKREVIEW_URL = get_env_variable(
    "MOSPI_QUICKREVIEW_URL",
    default="https://datainnovation.mospi.gov.in/api/quickreview",
)
MOSPI_PORTAL_ENABLED = get_env_variable("MOSPI_PORTAL_ENABLED", default=True, boolean=True)
MOSPI_PORTAL_VERIFY_SSL = get_env_variable("MOSPI_PORTAL_VERIFY_SSL", default=True, boolean=True)

MIDDLEWARE = [
    "config.middleware.FixDuplicateHostMiddleware",  # Fix duplicate host headers from proxy
    "config.middleware.SecurityHeadersMiddleware",  # Add security headers
    "config.middleware.RestrictHTTPMethodsMiddleware",  # Restrict HTTP methods
    "config.middleware.InputSanitizationMiddleware",  # Sanitize inputs
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"
ASGI_APPLICATION = "config.asgi.application"
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "postgres"),
            "USER": os.getenv("POSTGRES_USER", "postgres"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "postgres"),
            "HOST": os.getenv("DB_HOST", "db"),
            "PORT": os.getenv("DB_PORT", "5432"),
        }
    }

FILE_TABLE_POSTGRES_DB = os.getenv("FILE_TABLE_POSTGRES_DB", "postgres")
FILE_TABLE_POSTGRES_USER = os.getenv("FILE_TABLE_POSTGRES_USER", "postgres")
FILE_TABLE_POSTGRES_PASSWORD = os.getenv("FILE_TABLE_POSTGRES_PASSWORD", "postgres")
FILE_TABLE_DB_HOST = os.getenv("FILE_TABLE_DB_HOST", "file_data_db")
FILE_TABLE_DB_PORT = os.getenv("FILE_TABLE_DB_PORT", "5432")

SQLALCHEMY_ENGINE = create_engine(
    f"postgresql://{FILE_TABLE_POSTGRES_USER}:{FILE_TABLE_POSTGRES_PASSWORD}@{FILE_TABLE_DB_HOST}:{FILE_TABLE_DB_PORT}/{FILE_TABLE_POSTGRES_DB}"
)


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",  # noqa
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",  # noqa
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    # Limit OPTIONS response information for security (CWE-74)
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_METADATA_CLASS": "config.metadata.MinimalMetadata",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,  # Enable token rotation for security
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,  # Track login activity
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",
    "JTI_CLAIM": "jti",
    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),
}

# Account Lockout Settings
ACCOUNT_LOCKOUT_ATTEMPTS = 5
ACCOUNT_LOCKOUT_DURATION = timedelta(minutes=30)
ACCOUNT_LOCKOUT_RESET_TIME = timedelta(hours=24)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("redis", 6379)],
        },
    },
}

CELERY_BROKER_URL = get_env_variable(
    "CELERY_BROKER_URL", default="redis://redis:6379/0"
)
CELERY_RESULT_BACKEND = get_env_variable(
    "CELERY_RESULT_BACKEND", default="redis://redis:6379/0"
)
CELERY_RESULT_BACKEND = "django-db"

DOCLING_URL = get_env_variable("DOCLING_URL", default="https://docling:5001")

QDRANT_HOST = get_env_variable("QDRANT_HOST", default="http://qdrant")
QDRANT_PORT = get_env_variable("QDRANT_PORT", default="6333")
QDRANT_API_KEY = get_env_variable("QDRANT_API_KEY", default="abc123")
QDRANT_URL = f"{QDRANT_HOST}:{QDRANT_PORT}" if QDRANT_PORT else QDRANT_HOST
QDRANT_COLLECTION_NAME = get_env_variable("QDRANT_COLLECTION_NAME", "files")
QDRANT_QUERY_LIMIT = int(get_env_variable("QDRANT_QUERY_LIMIT", default=10))
QDRANT_EMBEDDING_MODEL = get_env_variable("QDRANT_EMBEDDING_MODEL", default="BAAI/bge-large-en-v1.5")
QDRANT_GPU_ENABLED = get_env_variable("QDRANT_GPU_ENABLED", default="1") == "1"
CHUNK_OVERLAP_TOKENS = int(get_env_variable("CHUNK_OVERLAP_TOKENS", default=500))
QDRANT_CACHE_DIR = get_env_variable("QDRANT_CACHE_DIR", default="/app/.qdrant_cache")

# AI Comments LLM Configuration (OpenAI for generating AI comments)
AI_COMMENTS_LLM_TYPE = get_env_variable("AI_COMMENTS_LLM_TYPE", default="openai")
AI_COMMENTS_LLM_API_KEY = get_env_variable("AI_COMMENTS_LLM_API_KEY", default="")
AI_COMMENTS_LLM_API_URL = get_env_variable("AI_COMMENTS_LLM_API_URL", default="")
AI_COMMENTS_LLM_API_VERSION = get_env_variable(
    "AI_COMMENTS_LLM_API_VERSION", default="2024-12-01-preview"
)
AI_COMMENTS_LLM_MODEL_NAME = get_env_variable(
    "AI_COMMENTS_LLM_MODEL_NAME", default="gpt-4o"
)

# SQL Query Generation LLM Configuration (Claude for generating SQL queries)
SQL_QUERY_LLM_TYPE = get_env_variable("SQL_QUERY_LLM_TYPE", default="claude")
SQL_QUERY_LLM_MODEL_NAME = get_env_variable(
    "SQL_QUERY_LLM_MODEL_NAME", default="claude-sonnet-4-20250514"
)

# Legacy LLM Configuration (kept for backward compatibility)
LLM_TYPE = get_env_variable("LLM_TYPE", default="ollama")
LLM_API_KEY = get_env_variable("LLM_API_KEY", default="abc123")
LLM_API_URL = get_env_variable("LLM_API_URL", default="http://localhost:11434")
LLM_API_VERSION = get_env_variable("LLM_API_VERSION", default="v1")
LLM_NAME = get_env_variable("LLM_NAME", default="llama3-70b-chat")
LLM_MAX_RETRIES = int(get_env_variable("LLM_MAX_RETRIES", default=5))
LLM_PROMPT_FOLDER = get_env_variable("LLM_PROMPT_FOLDER", default="./prompts")
LLM_VANNA_MODEL_NAME = get_env_variable("LLM_VANNA_MODEL_NAME", default=LLM_NAME)
LLM_LITELLM_MODEL_NAME = get_env_variable("LLM_LITELLM_MODEL_NAME", default=LLM_NAME)
ANTHROPIC_API_KEY = get_env_variable("ANTHROPIC_API_KEY", default="")
ANTHROPIC_MODEL = get_env_variable(
    "ANTHROPIC_MODEL", default="claude-sonnet-4-20250514"
)
# CORS Configuration - Strict security settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",  # Vite dev server
    "http://localhost:5174",  # Vite dev server (fallback port)
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",  # Vite dev server
    "http://127.0.0.1:5174",  # Vite dev server (fallback port)
    "https://mospi.edubildai.com",  # Production frontend domain
    "https://mospiapi.edubildai.com",  # Production API domain
    "https://statsdoc.ai.mospi.gov.in",  # Production MOSPI domain
    "http://103.48.43.155",
    "https://103.48.43.155",
]

# Only enable credentials for specific trusted origins
CORS_ALLOW_CREDENTIALS = True

# Disable allow all origins for security
CORS_ALLOW_ALL_ORIGINS = False

# Strict origin validation - only allow specific subdomains
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://mospi\.edubildai\.com$",
    r"^https://mospiapi\.edubildai\.com$",
    r"^https://statsdoc\.ai\.mospi\.gov\.in$",
]

# Additional CORS security headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Set max age for preflight requests
CORS_PREFLIGHT_MAX_AGE = 86400  # 24 hours
CSRF_TRUSTED_ORIGINS = [
    "https://mospi.edubildai.com",  # Production frontend domain
    "https://mospiapi.edubildai.com",  # Production API domain
    "https://statsdoc.ai.mospi.gov.in",  # Production MOSPI domain
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://103.48.43.155",
    "https://103.48.43.155",
]

# Strict ALLOWED_HOSTS - remove wildcard for security
ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "web",
    "mospi.edubildai.com",
    "mospiapi.edubildai.com",
    "statsdoc.ai.mospi.gov.in",
    "www.statsdoc.ai.mospi.gov.in",
    "103.48.43.155",
]

# Handle duplicate host headers from load balancer
USE_X_FORWARDED_HOST = True


# OCR Engine Configuration
OCR_ENGINE = get_env_variable("OCR_ENGINE", default="rapidocr")
OCR_LANG = get_env_variable("OCR_LANG", default="english").split(
    ","
)  # Split by comma for multiple languages

# Qdrant Embedding and Chunking Configuration
QDRANT_EMBEDDING_MODEL = get_env_variable("QDRANT_EMBEDDING_MODEL", default="BAAI/bge-small-en")
QDRANT_GPU_ENABLED = get_env_variable("QDRANT_GPU_ENABLED", default=False, boolean=True)
QDRANT_CACHE_DIR = get_env_variable("QDRANT_CACHE_DIR", default=str(BASE_DIR / ".qdrant_cache"))
CHUNK_OVERLAP_TOKENS = int(get_env_variable("CHUNK_OVERLAP_TOKENS", default="128"))