<script lang="ts">
    import * as AlertDialog from "$lib/components/ui/alert-dialog";
    import X from '@lucide/svelte/icons/x';

    let { open = $bindable(false) } = $props();
</script>

<AlertDialog.Root bind:open>
    <AlertDialog.Trigger asChild>
        {#snippet children({ props })}
            <slot {props}></slot>
        {/snippet}
    </AlertDialog.Trigger>
    <AlertDialog.Content class="sm:max-w-[700px]" oninteractoutside={() => open = false}>
        <button
            onclick={() => open = false}
            class="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-background transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 disabled:pointer-events-none"
            aria-label="Close"
        >
            <X class="h-4 w-4" />
            <span class="sr-only">Close</span>
        </button>

        <AlertDialog.Header>
            <AlertDialog.Title class="text-2xl">Disclaimer</AlertDialog.Title>
            <AlertDialog.Description>
                Important information about MoSPI StatsDoc AI Assistant
            </AlertDialog.Description>
        </AlertDialog.Header>

        <div class="space-y-4 py-4 text-sm text-gray-800">
            <p>
                The "MoSPI StatsDoc AI Assistant" is an Initiative of the Ministry of Statistics and Programme Implementation (MoSPI). The content and responses generated by this tool are intended solely to facilitate document search with the help of AI Enabled Intelligent Search.
            </p>
            <p>
                This chatbot is powered by third-party Large Language Models (LLMs) and fine-tuned to improve the user experience by searching through documents semantically, and despite the implementation of safeguards and guardrails, the responses generated should not be taken as evidence or treated as official communication. MoSPI shall not be liable for any loss, damage, or consequence arising from the use of this AI system.
            </p>
            <p>
                MoSPI makes no warranties regarding the accuracy, completeness, or reliability of the information provided. The Ministry and its staff, individually and collectively, shall not be liable for any financial or other consequences whatsoever arising from the use of this application, including but not limited to inappropriate, improper, or fraudulent use. Users are strongly cautioned to verify the accuracy and completeness of any information before relying on it for decision-making or any other purpose.
            </p>
        </div>
    </AlertDialog.Content>
</AlertDialog.Root>

<style>
    .text-sm { font-size: 0.875rem; }
</style>
